_wandb:
    value:
        cli_version: 0.24.0
        e:
            24rf8r3xl5k1ozwh5wfhcqiyrsyo36rl:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "253672886272"
                email: npalghat@andrew.cmu.edu
                executable: /opt/miniconda3/envs/handout/bin/python
                host: Narayanans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts/train.py
                python: CPython 3.12.12
                root: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts
                startedAt: "2026-02-28T00:25:38.457161Z"
                writerId: 24rf8r3xl5k1ozwh5wfhcqiyrsyo36rl
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
data:
    value:
        apply_filter: false
        use_all_directions: true
        use_all_speeds: true
model:
    value:
        min_segment_length: 200
        stride: 10
        subject_split:
            test_subjects:
                - AB10
            train_subjects:
                - AB06
                - AB07
                - AB08
                - AB11
                - AB12
                - AB13
                - AB14
            val_subjects:
                - AB09
        walking_directions:
            - cw
            - ccw
        walking_speeds:
            - fast
            - normal
            - slow
paths:
    value:
        data_root_dir: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/processed_zscore_data
run_dir:
    value: runs/model_v1_kernal_size_3_num_training_participants_7
