_wandb:
    value:
        cli_version: 0.24.0
        e:
            g70apq6otv0kd6xjtyyynshb7f9rshaf:
                apple: {}
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "235165941760"
                email: npalghat@andrew.cmu.edu
                executable: /opt/miniconda3/envs/handout/bin/python
                host: Narayanans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts/train.py
                python: CPython 3.12.12
                root: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts
                startedAt: "2026-03-07T04:24:24.247902Z"
                writerId: g70apq6otv0kd6xjtyyynshb7f9rshaf
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
activation:
    value: ReLU
batch_size:
    value: 32
data:
    value:
        apply_filter: false
        use_all_directions: true
        use_all_speeds: true
dropout:
    value: 0.15
dropout_type:
    value: Spatial
epochs:
    value: 6
kernel_size:
    value: 5
l1_reg:
    value: 0
l2_reg:
    value: 0
lr:
    value: 5e-05
model:
    value:
        min_segment_length: 200
        stride: 10
        subject_split:
            test_subjects:
                - AB10
            train_subjects:
                - AB06
                - AB07
                - AB08
                - AB11
                - AB12
                - AB13
                - AB14
            val_subjects:
                - AB09
        walking_directions:
            - cw
            - ccw
        walking_speeds:
            - fast
            - normal
            - slow
norm_type:
    value: WeightNorm
num_channels:
    value:
        - 80
        - 80
        - 80
        - 80
        - 80
paths:
    value:
        data_root_dir: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/processed_zscore_data
