_wandb:
    value:
        cli_version: 0.24.0
        e:
            t36z5f62m8tugehb5bdyanmnrzk0ryv6:
                apple: {}
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "256435761152"
                email: npalghat@andrew.cmu.edu
                executable: /opt/miniconda3/envs/handout/bin/python
                host: Narayanans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts/train.py
                python: CPython 3.12.12
                root: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts
                startedAt: "2026-03-07T08:39:35.077831Z"
                writerId: t36z5f62m8tugehb5bdyanmnrzk0ryv6
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
activation:
    value: ReLU
batch_size:
    value: 32
data:
    value:
        apply_filter: false
        use_all_directions: true
        use_all_speeds: true
dropout:
    value: 0.15
dropout_type:
    value: Spatial
emb_dim:
    value: 4
epochs:
    value: 10
feature_sets:
    value:
        active: mid
        full:
            - imu_foot_Accel_X
            - imu_foot_Accel_Y
            - imu_foot_Accel_Z
            - imu_foot_Gyro_X
            - imu_foot_Gyro_Y
            - imu_foot_Gyro_Z
            - imu_shank_Accel_X
            - imu_shank_Accel_Y
            - imu_shank_Accel_Z
            - imu_shank_Gyro_X
            - imu_shank_Gyro_Y
            - imu_shank_Gyro_Z
            - imu_thigh_Accel_X
            - imu_thigh_Accel_Y
            - imu_thigh_Accel_Z
            - imu_thigh_Gyro_X
            - imu_thigh_Gyro_Y
            - imu_thigh_Gyro_Z
            - fp_Treadmill_R_vy
            - fp_Treadmill_R_px
            - fp_Treadmill_R_pz
            - gon_ankle_sagittal
        mid:
            - imu_foot_Accel_X
            - imu_foot_Accel_Y
            - imu_foot_Accel_Z
            - imu_foot_Gyro_X
            - imu_foot_Gyro_Y
            - imu_foot_Gyro_Z
            - imu_shank_Accel_X
            - imu_shank_Accel_Y
            - imu_shank_Accel_Z
            - imu_shank_Gyro_X
            - imu_shank_Gyro_Y
            - imu_shank_Gyro_Z
            - fp_Treadmill_R_vy
            - fp_Treadmill_R_px
            - fp_Treadmill_R_pz
            - gon_ankle_sagittal
        minimal:
            - imu_foot_Accel_X
            - imu_foot_Accel_Y
            - imu_foot_Accel_Z
            - imu_foot_Gyro_X
            - imu_foot_Gyro_Y
            - imu_foot_Gyro_Z
            - fp_Treadmill_R_vy
            - fp_Treadmill_R_px
            - fp_Treadmill_R_pz
            - gon_ankle_sagittal
kernel_size:
    value: 5
l1_reg:
    value: 0
l2_reg:
    value: 0
lr:
    value: 5e-05
model:
    value:
        action_horizon:
            H: 10
            enabled: false
        min_segment_length: 300
        stride: 10
        subject_split:
            test_subjects:
                - AB10
            train_subjects:
                - AB06
                - AB07
                - AB08
                - AB11
                - AB12
                - AB13
                - AB14
                - AB15
                - AB16
                - AB17
                - AB18
                - AB19
                - AB20
            val_subjects:
                - AB09
        use_demographics: false
        use_subject_embedding: true
        walking_directions:
            - cw
            - ccw
        walking_speeds:
            - fast
            - normal
            - slow
norm_type:
    value: WeightNorm
num_channels:
    value:
        - 80
        - 80
        - 80
        - 80
        - 80
paths:
    value:
        data_root_dir: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/processed_zscore_data
        demographics_csv: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/csv_output/subject_info.csv
use_subject_embedding:
    value: true
