_wandb:
    value:
        cli_version: 0.24.0
        e:
            cacxx8wbo454otca66uraglzszf5mson:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: train_v2.py
                codePathLocal: train_v2.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "242589245440"
                email: npalghat@andrew.cmu.edu
                executable: /opt/miniconda3/envs/handout/bin/python
                host: Narayanans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts/train_v2.py
                python: CPython 3.12.12
                root: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts
                startedAt: "2026-02-27T23:53:38.759143Z"
                writerId: cacxx8wbo454otca66uraglzszf5mson
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
batch_size:
    value: 32
data:
    value:
        apply_filter: false
        use_all_directions: true
        use_all_speeds: true
epochs:
    value: 6
lr:
    value: 0.001
model:
    value:
        min_segment_length: 200
        stride: 10
        subject_split:
            test_subjects:
                - AB10
            train_subjects:
                - AB06
                - AB07
                - AB08
            val_subjects:
                - AB09
        walking_directions:
            - cw
            - ccw
        walking_speeds:
            - fast
            - normal
            - slow
num_params:
    value: 231425
paths:
    value:
        data_root_dir: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/processed_zscore_data
receptive_field:
    value: 181
