_wandb:
    value:
        cli_version: 0.24.0
        e:
            07v2pfg1u8lbdbigc47u4w171u4q033k:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "204096901120"
                email: npalghat@andrew.cmu.edu
                executable: /opt/miniconda3/envs/handout/bin/python
                host: Narayanans-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts/train.py
                python: CPython 3.12.12
                root: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/core/scripts
                startedAt: "2026-02-06T22:09:43.000937Z"
                writerId: 07v2pfg1u8lbdbigc47u4w171u4q033k
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
model:
    value:
        data_split:
            test: 0.1
            train: 0.8
            val: 0.1
        min_segment_length: 100
        stride: 10
        use_all_directions: true
        use_all_speeds: true
        walking_directions:
            - cw
            - ccw
        walking_speeds:
            - fast
            - normal
            - slow
paths:
    value:
        data_root_dir: /Users/narayanan/PycharmProjects/MRSD_exoskeleton/processed_zscore_data
